In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
array1 = np.genfromtxt('homes.csv',skip_header=1, delimiter = ',',usecols=(7,1,2,3,4,0))
array1[:5]

array([[2.2221e+04, 3.0320e+03, 4.0000e+00, 4.0000e+00, 2.0000e+00,
        3.6000e+05],
       [2.2912e+04, 2.0580e+03, 4.0000e+00, 2.0000e+00, 2.0000e+00,
        3.4000e+05],
       [2.1345e+04, 1.7800e+03, 4.0000e+00, 3.0000e+00, 2.0000e+00,
        2.5000e+05],
       [1.7342e+04, 1.6380e+03, 4.0000e+00, 2.0000e+00, 2.0000e+00,
        2.0550e+05],
       [2.1786e+04, 2.1960e+03, 4.0000e+00, 3.0000e+00, 2.0000e+00,
        2.7550e+05]])

In [32]:
x, y = array1[:,0:5], array1[:,5]
length=len(x)
x[0:10,]

array([[2.2221e+04, 3.0320e+03, 4.0000e+00, 4.0000e+00, 2.0000e+00],
       [2.2912e+04, 2.0580e+03, 4.0000e+00, 2.0000e+00, 2.0000e+00],
       [2.1345e+04, 1.7800e+03, 4.0000e+00, 3.0000e+00, 2.0000e+00],
       [1.7342e+04, 1.6380e+03, 4.0000e+00, 2.0000e+00, 2.0000e+00],
       [2.1786e+04, 2.1960e+03, 4.0000e+00, 3.0000e+00, 2.0000e+00],
       [1.8902e+04, 1.9660e+03, 4.0000e+00, 3.0000e+00, 5.0000e+00],
       [1.8639e+04, 2.2160e+03, 3.0000e+00, 2.0000e+00, 2.0000e+00],
       [2.2112e+04, 1.5970e+03, 2.0000e+00, 1.0000e+00, 1.0000e+00],
       [1.4321e+04, 1.6220e+03, 3.0000e+00, 2.0000e+00, 2.0000e+00],
       [3.2358e+04, 1.9760e+03, 3.0000e+00, 3.0000e+00, 1.0000e+00]])

In [ ]:
x1 = np.c_[np.ones(length), x]
x1[:5]

In [93]:
b1 = np.dot(x1.T,x1)
b1 = np.linalg.inv(b1)
b1

array([[ 3.95354381e-02, -2.32635657e-07, -3.76756460e-06,
        -4.84344907e-03,  2.32175909e-03, -6.07446762e-03],
       [-2.32635657e-07,  1.45485727e-11, -1.45824966e-11,
        -7.82953602e-09, -4.68833483e-09, -2.35182599e-08],
       [-3.76756460e-06, -1.45824966e-11,  1.01180074e-08,
        -1.18094436e-06, -3.74299516e-06, -2.26833059e-06],
       [-4.84344907e-03, -7.82953602e-09, -1.18094436e-06,
         2.97768652e-03, -1.07843728e-03,  1.03144822e-04],
       [ 2.32175909e-03, -4.68833483e-09, -3.74299516e-06,
        -1.07843728e-03,  4.43920039e-03, -8.23847440e-04],
       [-6.07446762e-03, -2.35182599e-08, -2.26833059e-06,
         1.03144822e-04, -8.23847440e-04,  6.47442651e-03]])

In [94]:
b2 = np.dot(x1.T,y)
b2

array([1.45060745e+08, 3.72329840e+12, 3.69799666e+11, 5.33671316e+08,
       4.35496879e+08, 3.31723936e+08])

In [96]:
coeffs = np.dot(b1, b2)
coeffs

array([-1.13113307e+05,  1.00804986e+00,  1.28056651e+02, -1.47934409e+04,
        1.96186361e+04,  3.64244996e+04])

In [98]:
coeffs2 = coeffs.reshape(-1,1)
coeffs2

array([[-1.13113307e+05],
       [ 1.00804986e+00],
       [ 1.28056651e+02],
       [-1.47934409e+04],
       [ 1.96186361e+04],
       [ 3.64244996e+04]])

In [39]:
lotsizemedian = np.median(x[:,0])
lotsizemedian

22200.0

In [40]:
areamedian = np.median(x[:,1])
areamedian

2061.0

In [41]:
bedmedian = np.median(x[:,2])
bedmedian

3.0

In [42]:
bathmedian = np.median(x[:,3])
bathmedian

3.0

In [43]:
garagemedian = np.median(x[:,4])
garagemedian

2.0

In [101]:
newval = np.array([[1,lotsizemedian,areamedian,bedmedian,bathmedian,garagemedian]])
newval

array([[1.000e+00, 2.220e+04, 2.061e+03, 3.000e+00, 3.000e+00, 2.000e+00]])

In [102]:
newval.shape

(1, 6)

In [103]:
np.dot(newval,coeffs2)

array([[260514.74311249]])